### ISSUE TITLE
Health doesn't decrease when hit

### ISSUE THREAD

**Issue by mishaelnuh** [Sudoblark/Butterchase#4]
UNLIMITED HP

![](https://media.tenor.com/images/89771f44ac2e35f60ded97efdfb45fa0/tenor.gif)

**Comment by mishaelnuh** [comment]
Sometimes

**Comment by Sudoblark** [comment]
I think this might have been to do with how the game calculates how to apply damage within the ```Character``` base class:
```py
 def do_damage(self, enemy, isTired):
        # Calculate damage and subtract chars defence
        damage = randint(self.adjustedAttack[0], self.adjustedAttack[1]) - enemy.adjustedDefence
        # See if enemy evades
        if randint(enemy.evadeAttack[0],enemy.evadeAttack[1]) == 1:
            damage = 0
            evaded = True
        else:
            evaded = False
        # If char is tired,enemy has not evaded, and damage is greater than one
        if (isTired) & (evaded == False) & (damage > 1):
            damage = damage // 2
        # Calculcate enemy new health if enemy did not evade and damage was dealt
        if (evaded == False)  & damage > 0:
            enemy.health = enemy.health - damage
        # Print results
        self.print_damage(enemy, damage, evaded)
        # Return if dead
        return enemy.health <= 0
```

With the above I wasn't able to replicate the issue until I was 4 goblins deep. I think the issue was that whilst damage was calculated, this was not being applied because of a typo:

```py
        if (evaded == False)  & damage > 0:
            enemy.health = enemy.health - damage
```
After changing this to:
```py
        if (evaded == False)  & (damage > 0):
            enemy.health = enemy.health - damage
```
Damage was applied to the player across 4 games and 6 attacks by 8 Goblins. Still going to keep the issue open but it might be fixed now.

**Comment by Sudoblark** [comment]
Once the content is created for all classes we can effectively test this on the dev level by having the player try and fight every single monster type.
